question_data =[
 {"category": "History", "type": "boolean", "difficulty": "medium",
  "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "easy",
  "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Music", "type": "boolean",
  "difficulty": "medium",
  "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Film", "type": "boolean",
  "difficulty": "easy",
  "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Science: Mathematics", "type": "boolean",
  "difficulty": "easy",
  "question": "A universal set, or a set that contains all sets, exists.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "General Knowledge", "type": "boolean",
  "difficulty": "easy",
  "question": "Nutella is produced by the German company Ferrero.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "hard",
  "question": "In the game &quot;Melty Blood Actress Again Current Code&quot;, you can enter Blood Heat mode in Half Moon style.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Science: Computers", "type": "boolean",
  "difficulty": "medium",
  "question": "&quot;Windows NT&quot; is a monolithic kernel.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "General Knowledge", "type": "boolean",
  "difficulty": "medium",
  "question": "You are allowed to sell your soul on eBay.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Politics", "type": "boolean", "difficulty": "easy",
  "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "easy",
  "question": "Minecraft can be played with a virtual reality headset.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
  "question": "Ferrari has never made a V10 engine for any of its cars.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Music", "type": "boolean",
  "difficulty": "easy",
  "question": "A Saxophone is a brass instrument.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
  "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "Pistons were added to Minecraft in Beta 1.5.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Film", "type": "boolean",
  "difficulty": "medium",
  "question": "Joan Cusack starred in the 2009 disaster movie, &quot;2012&quot;.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Animals", "type": "boolean", "difficulty": "easy",
  "question": "Cats have whiskers under their legs.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Television", "type": "boolean",
  "difficulty": "easy",
  "question": "In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Television", "type": "boolean",
  "difficulty": "medium",
  "question": "In &quot;Star Trek&quot;, Klingons respect William Shakespeare, they even suspect him having a Klingon lineage.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "In Portal, the Companion Cube&#039;s ARE sentient.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Science & Nature", "type": "boolean",
  "difficulty": "medium", "question": "Sugar contains fat.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Japanese Anime & Manga",
  "type": "boolean", "difficulty": "medium",
  "question": "In &quot;JoJo&#039;s Bizarre Adventure&quot;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
  "difficulty": "easy",
  "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Music", "type": "boolean",
  "difficulty": "medium",
  "question": "Nick Mason is the only member to appear on every Pink Floyd album.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Geography", "type": "boolean", "difficulty": "easy",
  "question": "Nova Scotia is on the east coast of Canada.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Geography", "type": "boolean", "difficulty": "easy",
  "question": "Rhode Island is actually located on the US mainland, despite its name.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
  "difficulty": "medium",
  "question": "Night on Bald Mountain was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
  "difficulty": "medium",
  "question": "Nutcracker Suite was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "easy",
  "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Geography", "type": "boolean", "difficulty": "hard",
  "question": "Only one country in the world starts with the letter Q.",
  "correct_answer": "True", "incorrect_answers": ["False"]}
 ]
